- CHANGELOG.md
- examples/TextInput/BasicUsage.js
- examples/TextLabel/Editable.js
- src/EditableBasicRow.js
- src/EditableText.js
- src/EditableTextLabel.js
- src/Text.js
- src/TextInput.js
- src/__tests__/EditableBasicRow.test.js
- src/__tests__/EditableText.test.js
- src/__tests__/EditableTextLabel.test.js
- src/__tests__/TextInput.test.js
- src/index.js
- src/mixins/withStatus.js
- src/styles/EditableBasicRow.scss
- src/styles/Text.scss
Split out `<EditableBasicRow>` which handles the input from `<EditableText>` , so each `Editable*` components can be more focused.
1. The input parts are moved into a new `<EditableBasicRow>`. It renders an `<input>` inside along with the basic label showing what you read on the input.
2. `<EditableText>` is simplified to only passes to/removes the status-related props from `<EditableBasicRow>`.
3. `<TextInput>` is thus simplified to just pass props to `<EditableText>`.
4. `<EditableTextLabel>` is now the only component that's responsible for managing input value changes. It discards input on `Esc` key, and report the input value on `Enter` key and input blurs.
5. Flow annotations for `Editable*` components.
> Refactor editable components

- CHANGELOG.md
- examples/EditableText/MultiLines.js
- examples/EditableText/index.js
- examples/TextInput/MultiLines.js
- examples/TextInput/index.js
- src/EditableBasicRow.js
- src/__tests__/EditableBasicRow.test.js
- src/__tests__/EditableTextLabel.test.js
- src/styles/EditableBasicRow.scss
Supports inputs in multiple lines
1. Add `inputTag` prop to `<EditableBasicRow>` so it can be `input` (for single-line) or `textarea` (for multiple lines).
2. Set `white-space: pre-wrap` to the basic label in `<EditableBasicRow>` to correctly display line-breaks and white-spaces from `<textarea>`. This also ensures the `<textarea>` can grow automatically when you add more lines.
3. Update examples and tests
#63 Refactor editable components
> Multi-lines <textarea> input

- CHANGELOG.md
- examples/DebugBox.js
- examples/HeaderRow/BasicUsage.js
- examples/HeaderRow/index.js
- examples/List/NormalList.js
- examples/List/SettingList.js
- examples/List/index.js
- src/HeaderRow.js
- src/List.js
- src/ListRow.js
- src/TextEllipsis.js
- src/__tests__/HeaderRow.test.js
- src/__tests__/List.test.js
- src/__tests__/ListRow.test.js
- src/__tests__/SearchInput.test.js
- src/__tests__/Text.test.js
- src/index.js
- src/mixins/__tests__/anchored.test.js
- src/mixins/__tests__/rowComp.test.js
- src/mixins/__tests__/withStatus.test.js
- src/styles/BasicRow.scss
- src/styles/Icon.scss
- src/styles/List.scss
- src/styles/ListRow.scss
- src/styles/_variables.scss
- src/utils/__tests__/getComponentName.test.js
- src/utils/__tests__/icBEM.test.js
- src/utils/icBEM.js
Add basic containers of `<HeaderRow>`, `<List>` (as a section) and `<ListRow>`
1. Add `<HeaderRow>` which is split into 3 areas: `left`, `center`, and `right`.
2. Add `<List>` as the list section, which contains `<ListRow>` as well as a title and a description block.
3. Add simple `<ListRow>` containing a Flexbox body for row components.
> Containers: Header and List

- CHANGELOG.md
- examples/ColumnView/BasicUsage.js
- examples/ColumnView/index.js
- examples/HeaderRow/BasicUsage.js
- src/ColumnView.js
- src/HeaderRow.js
- src/__tests__/ColumnView.test.js
- src/index.js
- src/styles/ColumnView.scss
- src/styles/HeaderRow.scss
- src/styles/_colors.scss
- src/styles/_variables.scss
Migrate <ColumnView> for web apps.
1. Add `<ColumnView>` and its styles. It's a vertical Flexbox which preserves a `header` and a `footer` blocks.
2. Fix styles for `<HeaderRow>` that doesn't match design.
3. Slightly enhance `<Button>` hover and active color so it's more obvious.
> Column view

- CHANGELOG.md
- examples/Popup/BasicPopup.js
- examples/Popup/EscapablePopup.js
- examples/Popup/index.js
- src/Overlay.js
- src/Popup.js
- src/__tests__/Overlay.test.js
- src/__tests__/Popup.test.js
- src/index.js
- src/mixins/__tests__/escapable.test.js
- src/mixins/escapable.js
- src/styles/Overlay.scss
- src/styles/Popup.scss
- src/styles/_colors.scss
- src/styles/_mixins.scss
- src/styles/_variables.scss
- src/styles/index.scss
- src/utils/__tests__/getComponentName.test.js
Add `<Popup>` component.
- Add `<Popup>` component and related examples.
- Add z-index sass mixin, which migrate from iC-framework.
- Add `escapable` HOC, which able to listening `Esc` key to trigger `onEscape` callback.
- Add page overlay `<Overlay>` component, formerly known as `<Backdrop>`.
> <Popup> component

- CHANGELOG.md
- examples/TextLabel/Editable.js
- src/EditableTextLabel.js
- src/__tests__/EditableTextLabel.test.js
1. Fix `<EditableTextLabel>` not supporting custom icon.
2. `<EditableTextLabel>` now does not fire `onEditRequest` callback, leaving users to decide when to control its editing state.
3. `<EditableTextLabel>` now simulates double-touch and then triggers `onDblClick` callback.
4. When the `inEdit` prop isn't set on `<EditableTextLabel>`, it becomes an uncontrolled component and will auto enter edit mode on double clicks.
> Enhance <EditableTextLabel>

- CHANGELOG.md
- examples/TextLabel/Editable.js
- package.json
- src/EditableTextLabel.js
- src/__tests__/EditableTextLabel.test.js
This release introduces API changes to `<EditableTextLabel>`
- API changes to `<EditableTextLabel>`:
* `inEdit` prop now defaults to `undefined`, which means the component is **uncontrolled**.
* When `inEdit` is set either `true` or `false`, the component is **controlled**
* ~`onEditRequest`~ prop is removed in favor of new `onDblClick` callback. Users can decide when to update the edit state.
- Behavior changes to `<EditableTextLabel>`:
* Custom element passed via `icon` now renders correctly under edit mode
* Double touch on mobile devices also triggers `onDblClick` callback.
* If component is **uncontrolled**, it auto enters edit mode on double clicks/touches and leaves on edit ends.
> Release 1.1.0

- CHANGELOG.md
- src/Button.js
- src/__tests__/Button.test.js
- src/styles/Button.scss
- src/styles/index.scss
The issue comes from a Safari/Webkit bug where `<button>` behaves slightly different as a Flex box. This makes a `<Button align="center" minified={false} />` unable to place its content at the center of whole component.
The bug is addressed in Safari 11. But for backward compatibility, the underlying tag for `<Button>` is changed to `<div>` until Safari 11 gets widely adapted.
Ref: https://stackoverflow.com/questions/35464067/flexbox-not-working-on-button-element-in-safar
> Fix <Button> contents not center-aligned in expanded mode in Safari

- CHANGELOG.md
- src/EditableBasicRow.js
- src/EditableText.js
- src/EditableTextLabel.js
- src/TextInput.js
- src/__tests__/EditableBasicRow.test.js
- src/mixins/rowComp.js
Clarify the behaviors of editable components, update them in a shared logic.
1. Update comments for editable components to clarify usage and behavior
2. `<EditableBasicRow>` now passes all unknown props to its underlying input.
3. `<EditableTextLabel>` filters out `status` from its inner `<TextLabel>` when it's in edit mode.
> Update editable components

- CHANGELOG.md
- src/styles/Text.scss
- src/styles/_colors.scss
Align `<Text>` with new design spec.
1. The “basic” text is now in bold font.
2. The “aside” text is now slighter in color.
> Update <Text> with new design spec

- .travis.yml
This should enable `lerna publish` script with the same approach we once used in `deploy.sh`
> Use the .npmrc approach to auth 'lerna publish'

- lerna.json
- package.json
- yarn.lock
It turned out that the default NPM registry config on Travis CI is somehow broken, which finally led to the failure of publish.
This should closes #85.
1. Fix `npm publish` failure by manually specify registry URL.
2. Upgrade to [Lerna 2.4.0](https://github.com/lerna/lerna/releases/tag/v2.4.0) for improved exit code
> Fix deloy issues

- configs/jest.config.json
- packages/form/configs/webpack.dist.js
- packages/form/package.json
- packages/form/src/TextInput.js
- packages/form/src/__tests__/TextInput.test.js
- packages/form/src/index.js
- packages/form/src/mixins/__tests__/formRow.test.js
- packages/form/src/mixins/formRow.js
- packages/form/src/styles/TextInput.scss
- packages/storybook/examples/Form.TextInput/BasicUsage.js
- packages/storybook/examples/Form.TextInput/index.js
- packages/storybook/package.json
Add an row-based input with alternative behaviors form new design spec.
1. Create new package `@ichef/gypcrete-form` for new row-based form components
2. Create new `<TextInput>` and its styles
3. Fix Jest should not ignore `node_modules/@ichef/*` when transforming files.
> Add new <TextInput> for form package

- package.json
- packages/storybook/.storybook/Code.js
- packages/storybook/.storybook/config.js
- packages/storybook/.storybook/preview-head.html
- packages/storybook/examples/.eslintrc.yml
- packages/storybook/package.json
- yarn.lock
First todo item of #81.
Upgrade storybook to v3.2 for react 16 ready.
- Upgrade storybook libraries to `v3.2.12`,
- List storybook and react libraries as `dependencies` in **@ichef/gypcrete-storybook** package. Since the storybook was moved from core package, they should not listed as `devDependencies` anymore.
- Fix the markdown issue of addon-info. (Issue: storybooks/storybook#1662)
- Temporarily remove the header of addon-info.
* `inline` styling is damn strange now, the header and preview parts are split into separate shadowed containers. (Issue: storybooks/storybook#1877)
Since header is removed, add some lighten grid background in preview. Just a try 😬
> Upgrade storybook to v3.2

- CHANGELOG.md
- packages/core/src/styles/HeaderRow.scss
- packages/core/src/styles/ListRow.scss
- packages/core/src/styles/Text.scss
- packages/core/src/styles/_variables.scss
- packages/storybook/examples/List/NormalList.js
Fix styles that does not match design spec.
Fixes #100.
- [Core] Fix aside label for `<Text>` should turn white inside a highlighted `<ListRow>`.
- [Core] Adds hover background for `<ListRow>`.
- [Core] Fix vertical padding for `<HeaderRow>`.
> Fix component styles

- CHANGELOG.md
- packages/core/configs/webpack.dist.js
- packages/form/configs/webpack.dist.js
The CSS bundle generated by v1.3.1 has broken path for font files, pointing to non-existing `fonts/fonts/`.
This fixes the double-fonts issue by removing `publicPath` from webpack config.
> Fix bundled CSS reading fonts from 'fonts/fonts/' path

- CHANGELOG.md
- packages/core/src/mixins/__tests__/anchored.test.js
- packages/core/src/mixins/anchored.js
- packages/core/src/mixins/closable.js
- packages/core/src/styles/Popover.scss
- packages/form/src/SelectRow.js
- packages/form/src/__tests__/SelectRow.test.js
- packages/form/src/styles/SelectRow.scss
- packages/storybook/examples/Form.SelectRow/BasicUsage.js
- packages/storybook/examples/Form.SelectRow/index.js
Add a row-based component which lets you to pick options from a `<SelectList>` rendered inside a `<Popover>`
- Add new `<SelectRow>`, which takes `<SelectOption>` as children and renders `<SelectList>` inside a popover when user clicks on the row.
> [form] Add <SelectRow>

- package.json
When publishing canary builds, by default Lerna uses carets on package versions.
This means the dependency version will be something like `^1.4.0-alpha.758a88c0`
However the caret here may have npm/yarn resolve to an older version, because npm cannot compare git hashes.
This PR set package version to exactly the same version on canary builds, so you don't get incompatible versions.
> Publish canary builds with exact package version

- CHANGELOG.md
- packages/form/src/SelectList.js
- packages/form/src/SelectRow.js
- packages/form/src/__tests__/SelectList.test.js
- packages/form/src/__tests__/SelectRow.test.js
- packages/form/src/utils/__tests__/parseSelectOptions.test.js
- packages/form/src/utils/parseSelectOptions.js
A `<SelectRow>` should display its current values at the `aside` area.
1. Extract `parseSelectOptions()` helper to read from children of `<SelectOption>`s.
2. `<SelectRow>` now caches values internally, and use that to control `<SelectList>`
3. Customize display labels for `<SelectRow>` with `asideAll`, `asideNone` and `asideSeparator`.
4. `<SelectList>` now passes sorted values via `onChange()`
> Add values display for <SelectRow>

- CHANGELOG.md
- packages/core/src/mixins/__tests__/closable.test.js
- packages/core/src/mixins/closable.js
- packages/storybook/examples/Popover/DemoList.js
Some `click` events are blocked if they are fired from components inside a `closable()` HOC, if the later is configured to close on inside clicks. The main reason if because the component is removed from React virtual DOM tree by the `onClose` callback triggered on `closable()`.
Always delay `onClose()` callback for `closable()` HOC for both clicks and touches.
> Fix closable() blocking children events

- CHANGELOG.md
- packages/core/src/IconButton.js
- packages/core/src/ListRow.js
- packages/core/src/mixins/__tests__/rowComp.test.js
- packages/core/src/mixins/rowComp.js
- packages/core/src/styles/Button.scss
- packages/storybook/examples/List/NormalList.js
1. [Core] Add `tinted` prop for `<IconButton>` for a half-transparent icon.
2. [Core] `<ListRow>` stops forwarding status props to children via context. This is changed against `v1.2.0`.
> Style tweaks

- CHANGELOG.md
- packages/core/src/IconButton.js
- packages/core/src/__tests__/IconButton.test.js
`<IconButton>` injects up to 2 BEM class names to `<Button>`:
- `gyp-button--icon-only`
- `gyp-button--tinted`
However they can be overridden if you set a custom `className` prop on it.
Use `classnames` helper to combine all class names.
> Fix <IconButton> injected class overridden by custom class

- CHANGELOG.md
- packages/core/src/mixins/__tests__/closable.test.js
- packages/core/src/mixins/closable.js
- packages/form/src/SwitchRow.js
- packages/form/src/TextInputRow.js
- packages/form/src/__tests__/SwitchRow.test.js
- packages/form/src/__tests__/TextInputRow.test.js
- packages/form/src/mixins/__tests__/formRow.test.js
- packages/form/src/mixins/formRow.js
Enhance `<TextInputRow>` and other components so it's easier to create variation of input rows.
- [Core] `closable()` HOC mixin now takes runtime options via props.
- [Form] `<TextInputRow>` and `<SwitchRow>` now accepts `children` prop, will render inside `<ListRow>`.
- [Form] `<TextInputRow>` now exposes ref to inner `<input>` via `getInputNode()` method. 
I was considering to bundle [`react-dates`](https://github.com/airbnb/react-dates) into `gypcrete-form` as a date row with built-in date picker. But later I think it's better to keep the package simple and focused for now.
> Enhance extendibility for a few components

- CHANGELOG.md
- packages/core/src/styles/Popover.scss
- packages/core/src/styles/_variables.scss
- packages/form/src/SelectRow.js
- packages/form/src/styles/SelectRow.scss
- packages/form/src/styles/TextInputRow.scss
Patches to enhance component behavior
- [Core] Fix `<Popover>` should have `max-height` while making its content scrollable. (#120)
- [Form] Fix unset `<SelectRow>` showing 'All' when it has no option. (#120)
- [Form] Fix unset `<SelectRow>` label should be tinted. (#120)
> Layout fixes for <Popover> and appearance tweak for <SelectRow>

- CHANGELOG.md
- lerna.json
- package.json
- packages/core/package.json
- packages/core/src/mixins/closable.js
- packages/core/src/styles/Popover.scss
- packages/form/package.json
- packages/form/src/SelectRow.js
- packages/storybook/examples/Form.SelectRow/Customize.js
- packages/storybook/examples/Form.SelectRow/MultipleValues.js
- packages/storybook/examples/Form.SelectRow/index.js
- packages/storybook/package.json
- [Form] The popover inside a single-value `<SelectRow>` should now close automatically after click on any option. (#125)
- [Form] Update examples for `<SelectRow>`. (#125)
- [Core] Fix `<Popover>` should only scroll its container. (#125)
> Release 1.5.2

- CHANGELOG.md
- packages/core/src/mixins/renderToLayer.js
- packages/core/src/styles/Overlay.scss
- packages/core/src/styles/Popover.scss
- packages/core/src/styles/Popup.scss
- packages/core/src/styles/RenderToLayer.scss
- packages/core/src/styles/_mixins.scss
- packages/core/src/styles/_variables.scss
Components that are rendered into an external layer (a *base layer*) were set with pre-defined `z-index` to stack above other components. The problem is you'll be unable to place a component set with a lower `z-index` above one with a higher `z-index`.
For example, a `<Popover>` (defined at `z-index` of `100`) will always be blocked by a `<Modal>` (defined at `z-index` of `999` in ic-framework. Not yet available in gypcrete.) But in practice, it's often to render a `<Popover>` above the later, in the case of “opening a menu inside a modal”.
This PR assumes every render-to-layer component that is opened later, should be place more closed to foreground. Therefore every newly-inserted base layer should be place above previous layers. And by creating a stacking context for every base layer, …
> Stack base layers with stacking context

- packages/core/src/styles/RenderToLayer.scss
Fixes the issue from: https://github.com/iCHEF/gypcrete/pull/129#issuecomment-357139990
> Fix base layer should be as wide as viewport to not supress its content

- .travis.yml
- CHANGELOG.md
- packages/core/src/__tests__/Button.test.js
1. Fix failing `<Button>` tests.
2. Workaround fix CI not aware of failing tests.
Jest exits with `0` even with failing tests.
This PR adds a quick workaround by adding `--bail` option to `yarn test` script.
It make Jest to break and exit with 1 immediately on first failure.
> Fix <Button> tests

- CHANGELOG.md
- packages/core/src/Modal.js
- packages/core/src/__tests__/Modal.test.js
- packages/storybook/examples/Modal/index.js
- Fix the problem that `<Modal>` is not rendering modal content
- Prevent unexpected closing behaviors occur when more than one modals are open.
1. Pass children back to `<ClosableModalContent>`
2. Add `<div>Modal Content</div>` into examples  in the storybook
3. Add a test case to test if the modal content is rendered properly
4. Remove the `Closable` HOC from `<Modal>` to prevent unexpected closing behaviors occur when more than one modals are open.
> Fix <Modal> not rendering its content and prevent unexpected closing behaviors

- CHANGELOG.md
- packages/core/src/Modal.js
- packages/core/src/__tests__/Modal.test.js
- packages/core/src/styles/Modal.scss
- packages/storybook/examples/Modal/BasicModal.js
- packages/storybook/examples/Modal/index.js
Add a function to close the `<Modal>` when users click the outer `<Overlay>` and the onClose prop exists.
When there are multiple `<Modal>`s open at the same time, the inner `<Modal>` is to be closed first when users click the outer `<Overlay>` .
Please note that `Closable` HOC cannot be used in `<Modal>`, since it registers closing events to the document which causes the outer `<Modal>` to be closed first.
- Add an onClick event to `<Overlay>` to stop the propagation of click events.
- Call onClose if it exists and `<Overlay>` is clicked.
> Add a function to close the `<Modal>` when users click `<Overlay>`

- CHANGELOG.md
- packages/core/src/styles/Popover.scss
- packages/form/src/SelectRow.js
Address issues related to `<Popover>` 
- [Core] Fix some content might exceed `<Popover>` container
- [Form] Fix `<Popover>` inside `<SelectRow>` should not be closed until user clicks on the checkbox.
> Fix <Popover>

- CHANGELOG.md
- packages/imageeditor/src/__tests__/index.test.js
- packages/imageeditor/src/index.js
Enhance `<ImageEditor>` to better match existing usage of the version in `ic-framework-react`.
- Proxy `onLoadSuccess` callback of `<AvatarEditor>` and adds cropping rect as 2nd param
- Add accessor method for getting internal ref to `<AvatarEditor>`.
N/A
> Enhance <ImageEditor>

- CHANGELOG.md
- packages/form/src/TextInputRow.js
- packages/form/src/__tests__/TextInputRow.test.js
- packages/storybook/examples/Form.TextInputRow/ControlledRow.js
- packages/storybook/examples/Form.TextInputRow/MultiLineUsage.js
- packages/storybook/examples/Form.TextInputRow/index.js
Allow `<TextInputRow>` to render an auto-growing `<textarea>` instead for multi-line contents.
- Add `multiLine` prop to `<TextInputRow>` to render `<textarea>`
- Add examples and update tests for updated `<TextInputRow>`
> Add multi-line mode for <TextInputRow>

- CHANGELOG.md
- packages/form/src/SelectList.js
- packages/form/src/SelectOption.js
- packages/form/src/utils/__tests__/getElementTypeSymbol.test.js
- packages/form/src/utils/getElementTypeSymbol.js
- packages/form/src/utils/parseSelectOptions.js
`react-hot-loader` v4 wraps every single component with a proxy for its internal uses.
This breaks `<SelectList>` when it reads configs from children and compares every child's `type` to `<SelectOption>`, because those `type`s are proxied.
To avoid the side effect, I've add a `SelectOption.typeSymbol` to be used for comparison instead.
- [Form] Add new `SelectOption.typeSymbol` for element type comparison.
- [Form] Add `getElementTypeSymbol` helper for getting type symbol from React Element.
> Check <SelectOption> with symbol instead

- CHANGELOG.md
- packages/form/src/SelectRow.js
- packages/form/src/__tests__/SelectRow.test.js
The popover inside `<SelectRow>` is closed automatically after value changes.
While this is desired behavior under single-selection mode, it should be prevented under multiple mode.
- [Form] Fix Popover inside `<SelectRow>` should not auto-close under multiple selection mode.
- [Form] Refactor `<SelectRow>` to use `<Popover>` directly from core package, and controls its `closable` behavior via props.
> Fix Popover inside <SelectRow> to not auto-close under multiple mode

- CHANGELOG.md
- packages/core/src/Button.js
- packages/core/src/ListRow.js
- packages/core/src/Text.js
- packages/core/src/__tests__/Text.test.js
- packages/core/src/mixins/__tests__/rowComp.test.js
- packages/core/src/mixins/rowComp.js
- packages/core/src/styles/List.scss
- packages/core/src/styles/Text.scss
- [Core] Update styles to match design for: `<List>`.
- [Core] `<Button>`is now `bold` by default.
- [Core] `<Text>` and `rowComp()` now preserve white space by default.
- [Core] Fix `<ListRow>` footer should not render empty `<p>` tags.
> Various UI updates

- CHANGELOG.md
- packages/core/src/Text.js
- packages/core/src/__tests__/Text.test.js
- packages/core/src/mixins/__tests__/rowComp.test.js
- packages/core/src/mixins/rowComp.js
- packages/core/src/styles/List.scss
- packages/core/src/styles/ListRow.scss
- packages/core/src/styles/Tag.scss
- packages/core/src/styles/Text.scss
- packages/core/src/styles/Tooltip.scss
Preserve white spaces on core components.
- Reverted the optional `preserveWhitespace` prop on `<Text>` that was introduced in #159, since there are more places that needs to preserve white spaces and it's hard to maintain a unified prop way for that.
- Preserve white spaces on the following components:
* `<Text>` (which is in most row-components)
* `<List>` (in title and desc)
* `<ListRow>` (in desc)
* `<Tag>`
* `<Tooltip>`
I was thinking if we can introduce a span-level text component that manages styles (e.g. white-space preserving, text ellipsis) for text, and fill every text with that component.
But that will be a major breaking change, so I guess it should hold until 2.0
> Preserve white spaces

- CHANGELOG.md
- packages/core/src/EditableBasicRow.js
- packages/core/src/__tests__/EditableBasicRow.test.js
Remove the auto-blur behavior when `<input>` inside `<EditableBasicRow>` (which is the foundation of *editable* row components) receives new `status` prop.
In React 16 the input might be blurred before it's new value is updated to DOM.
Therefore can result in incorrect `value` in the blur event.
Besides, it doesn't seem to make sense to blur on status change now.
> Remove input auto-blur in editable components

- CHANGELOG.md
- packages/core/src/styles/List.scss
Fix the bug that the bottom border of the title in the normal `<List>` lacks a right margin.
- Asana: https://app.asana.com/0/347798529122928/739456602042129
- Add a right margin to the title in the normal `<List>`.
> [Fix] Bottom border of the list title lacks a right margin

- CHANGELOG.md
- packages/core/src/List.js
- packages/core/src/ListRow.js
- packages/core/src/Section.js
- packages/core/src/__tests__/List.test.js
- packages/core/src/__tests__/ListRow.test.js
- packages/core/src/__tests__/Section.test.js
- packages/core/src/index.js
- packages/core/src/styles/List.scss
- packages/core/src/styles/Section.scss
- packages/core/src/styles/_colors.scss
- packages/core/src/styles/_mixins.scss
- packages/core/src/styles/_variables.scss
- packages/storybook/examples/List/SettingList.js
- packages/storybook/examples/Section/DemoContent.js
- packages/storybook/examples/Section/index.js
- packages/storybook/utils/DebugBox.js
Extract the section layout into a new `<Section>` component out from `<List>`, so the it can be a more generalized wrapper which gives any content an optional title and desc block.
It can also provide left/right padding to components that *are not* row-based before putting into a container like `<ColumnView>`
- [Core] Add new `<Section>` layout component
- [Core] Update `<List>` to use `<Section>` as its own wrapper
- [Core] Update `<ListRow>` to force-set `verticalSpacing={false}` to nested `<List>` (and be passed to its inner `<Section>`)
> Extract <Section> layout from <List>

- CHANGELOG.md
- packages/core/src/mixins/__tests__/anchored.test.js
- packages/core/src/mixins/anchored.js
Fix horizontal position of components applied with `anchored()` mixin when the target anchor is larger than it self. It should always align to the center at such condition.
- Fix `adjustPosition()` in `anchored()` mixin
- Add tests for the case where anchor is larger than anchored box.
> [Fix] Fix anchored component alignment when anchor is larger than itself

- CHANGELOG.md
- packages/core/src/HeaderRow.js
- packages/core/src/__tests__/HeaderRow.test.js
- packages/core/src/styles/ColumnView.scss
- packages/core/src/styles/HeaderRow.scss
- packages/core/src/styles/_variables.scss
- packages/storybook/examples/HeaderRow/OptionalArea.js
- packages/storybook/examples/HeaderRow/index.js
Update styles for `<ColumnView>` and `<HeaderRow>` to better match design.
- [Core] Removed padding in `<ColumnView>` body.
- [Core] `<HeaderRow>` can now disable an area by setting `false` to it. Styles updated.
> Update column styles

- .flowconfig
- CHANGELOG.md
- packages/core/package.json
- packages/core/src/List.js
- packages/core/src/ListRow.js
- packages/core/src/Popover.js
- packages/core/src/__tests__/List.test.js
- packages/core/src/__tests__/ListRow.test.js
- packages/core/src/__tests__/Popover.test.js
- packages/core/src/contexts/listSpacing.js
- packages/core/src/styles/Popover.scss
- packages/core/src/styles/_variables.scss
- yarn.lock
`<List>` is now wrapped by `<Section>`, introduced in #166, with a notable vertical spacing by default.
However it used to have smaller spacing and thus it now looks awkward when placed inside certain components, like `<ListRow>` and `<Popover>`.
This PR tries to remove the extra spacing from `<List>` by default when it's put in given components.
- [Core] Add context for configuring vertical spacing for `<List>`.
- [Core] Remove vertical margin from `<List>` by context when placed inside `<ListRow>` or `<Popover>`.
> Remove <List> vertical spacing inside certain components

- CHANGELOG.md
- packages/form/src/SelectList.js
- packages/form/src/__tests__/SelectList.test.js
- packages/storybook/examples/Form.SelectList/MultipleWithoutCheckAll.js
- packages/storybook/examples/Form.SelectList/index.js
Add the `showCheckAll` prop to disable `checkAll` option in `<SelectList>` (By default, there is a `checkAll` option in the multiple `<SelectList>`).
- Add the `showCheckAll` prop to disable `checkAll` option in `<SelectList>`
> Add the showCheckAll prop to disable checkAll option in <SelectList>

- CHANGELOG.md
- packages/form/src/SelectList.js
Let `<SelectList>` accept the `title` and `desc` props to display the list title and description if they are provided.
- Let `<SelectList>` accept the `title` and `desc` props.
> Let SelectList accept the title and desc props 

- CHANGELOG.md
- packages/core/src/mixins/__tests__/closable.test.js
- packages/core/src/mixins/closable.js
- packages/storybook/examples/Popover/DemoList.js
Change `closable()` mixin to listen on `touchend` events on touch devices instead of `touchstart`.
So it should only close when your hand leaves the screen, not at the moment you tap it.
- [Core] `closable()` mixin is now triggered on `touchend` events on touch devices. 
- [Storybook] Update examples for `<Popover>` to add a row of hyperlink `<Button>`.
> Improve 'closable()' mixin triggering

- CHANGELOG.md
- packages/core/src/ColumnView.js
- packages/core/src/SplitView.js
- packages/core/src/SplitViewColumn.js
- packages/core/src/__tests__/ColumnView.test.js
- packages/core/src/__tests__/SplitView.test.js
- packages/core/src/__tests__/SplitViewColumn.test.js
- packages/core/src/index.js
- packages/core/src/styles/ColumnView.scss
- packages/core/src/styles/SplitView.scss
- packages/core/src/styles/_colors.scss
- packages/core/src/styles/_variables.scss
- packages/storybook/examples/core/SplitView/BasicUsage.js
- packages/storybook/examples/core/SplitView/ContainsColumnView.js
- packages/storybook/examples/core/SplitView/DemoColumnView.js
- packages/storybook/examples/core/SplitView/InsideColumnView.js
- packages/storybook/examples/core/SplitView/index.js
- packages/storybook/utils/ColoredBox.js
Add `<SplitView>` from ic-framework.
This should mark the final migration from ic-framework.
- [Core] Add new `<SplitView>` and `<SplitViewColumn>`.
- [Core] Update `<ColumnView>` layout styles; allow overriding bottom padding.
> Add <SplitView>

- CHANGELOG.md
- lerna.json
- package.json
- packages/core/package.json
- packages/form/package.json
- packages/imageeditor/package.json
- packages/storybook/package.json
- Organize storybook #177
- Add <SplitView> #178
- [Core] Add new `<SplitView>` and `<SplitViewColumn>`. (#178)
- [Storybook] Add examples for `<SplitView>` and its usage with `<ColumView>`. (#178)
- [Core] `closable()` mixin is now triggered on `touchend` events on touch devices. (#176)
- [Core] Update `<ColumnView>` layout styles; allow overriding bottom padding. (#178)
- [Storybook] Update examples for `<Popover>` to add a row of hyperlink `<Button>`. (#176)
- [Storybook] Split stories into different package-based sections. (#177)
> Release 1.10.0

- CHANGELOG.md
- packages/core/package.json
- packages/core/src/Icon.js
- packages/core/src/Modal.js
- packages/core/src/Overlay.js
- packages/core/src/Popup.js
- packages/core/src/mixins/__tests__/renderToLayer.test.js
- packages/core/src/mixins/renderToLayer.js
- packages/core/src/styles/index.scss
Use `ReactDOM.createPortal()` in `renderToLayer()` HOC mixin to replace previous `ReactDOM.unstable_renderSubtreeIntoContainer()` private API usage.
- [Core] Adapt React Portal in `renderToLayer()` HOC mixin.
- [Core] Slightly change the way we import CSS Animation to work better in Storybook.
> Adapt React Portal

- CHANGELOG.md
- packages/core/src/Modal.js
- packages/core/src/Popover.js
- packages/core/src/Tooltip.js
- packages/core/src/mixins/__tests__/anchored.test.js
- packages/core/src/mixins/anchored.js
- packages/form/package.json
- packages/imageeditor/package.json
As of React 16.6, `ReactDOM.findDOMNode()` is [added to list of deprecated API][1].
But even before that, usage of the API has been advised to be prevented.
This PR removes calls to the listed API from `anchored()` HOC mixin, and instead introduces an approach that requires you to manually set refs to both *anchor* element and *wrapped* element.
The `anchored(Component)` HOC now only accept an `HTMLElement` node for the `anchor` prop it's taking.
Also it now passes an additional `nodeRef` prop to the wrapped component, which is a `React.createRef()` to collect ref to the DOM node that should be positioned to anchor.
```js
function Component({ placement, arrowStyle, style, nodeRef }) {
return (
<div ref={nodeRef} className={placement} style={style}>
<div className="arrow" …
```
> Remove usage of React.findDOMNode()

- CHANGELOG.md
- packages/core/src/mixins/closable.js
`clickedInside` and `closeDelayTimeout` are only used inside internal event listeners to determine if an outside-click event can be ignored when an inside-click event has already scheduled a close callback.
They were previously put inside component states, therefore triggers useless `render()` calls as they change while they never affect render results.
Moving them to instance variables saves a few calls to `render()`.
> Reduce useless render calls in 'closable()' mixin

- CHANGELOG.md
- packages/core/src/mixins/__tests__/closable.test.js
- packages/core/src/mixins/closable.js
Current event handlers inside `closable()` mixin (in `core/` package) fail to recognize a inside-click when it's configured not to close under this scenario. Therefore it fails to block `onClose()` callbacks.
This PR fixes the issue by correctly marking a inside-click inside handlers.
- [Core] Fix `closable()` mixin to or not to call `onClose()` correctly on inside-clicks.
- [Core] Update tests for `closable()` so it covers all config combinations.
The `it('triggers')` and `it('does not trigger')` test cases (6 cases in total) are replaced with `describe.each` and `test.each` test blocks.
It might be hard to read these changes from comparing diff, so please consider read the new test cases directly from the file.
> Fix 'closable()' not blocking 'onClose()' callback on inside-clicks

- CHANGELOG.md
- lerna.json
- package.json
- packages/core/package.json
- packages/core/src/mixins/__tests__/closable.test.js
- packages/core/src/mixins/closable.js
- packages/form/package.json
- packages/imageeditor/package.json
- packages/storybook/package.json
- #193 Fix 'closable()' not blocking 'onClose()' callback on inside-clicks
- [Core] Fix `closable()` mixin to or not to call `onClose()` correctly on inside-clicks. (#193)
> Release 2.0.1

- CHANGELOG.md
- packages/core/src/Modal.js
- packages/core/src/__tests__/Modal.test.js
- packages/core/src/styles/Modal.scss
- packages/storybook/examples/core/Modal/index.js
Make `Modal` on top of screen rather than centering by default.
* Add `centered` prop (which is boolean) on `Modal`, default to false. When it's false, the `gyp-modal` will be positioned on the top of screen, else it would be centered, where is the previous behavior.
* Update storybook for centered modal.
Default modal after this PR (top-right and top-left border-radius set to 0):
Modal with `center=true` (which is as same as previous modal):
None.
None.
> Add centered prop into Modal to make it on top of screen

- CHANGELOG.md
- packages/core/src/styles/Modal.scss
- packages/core/src/styles/_mixins.scss
- packages/core/src/styles/_variables.scss
- packages/storybook/examples/core/Modal/BasicModal.js
- packages/storybook/examples/core/Modal/index.js
Add indent for multiple modal
Change css width (and `max-width`) and height of modal that on top of others. Will reduce 8px for right, bottom and left side. When layer number > 7 we will not indent it.
UI Screenshot:
You could see that the top of modal is also indented, which could be fixed by add margin-top. But after #196 is merged, there's no need to add the margin to adjust this. See following screenshot:
None.
> Shorten width for multiple layer modal

- CHANGELOG.md
- packages/core/src/styles/ColumnView.scss
- packages/core/src/styles/Modal.scss
- packages/core/src/styles/_variables.scss
Adjust modal / column view padding.
- Add padding-bottom on modal, no matter `bodyPadding` prop is true or not.
- Remove padding-bottom on column view.
None.
None.
> Adjust modal and column view padding

- CHANGELOG.md
- packages/core/src/SearchInput.js
- packages/core/src/__tests__/SearchInput.test.js
- packages/core/src/styles/SearchInput.scss
- packages/core/src/styles/_variables.scss
- packages/storybook/examples/core/SearchInput/BasicSearchInput.js
- packages/storybook/examples/core/SearchInput/index.js
Refactor `<SearchInput>` and make it can be controlled.
- [Core] Change `<SearchInput>` behavior:
- Can be controlled now, via props `value`, `onChange` and `onReset`.
- No longer trigger `onSearch` when input blur by default. You can enable this behavior by setting prop `searchOnInputBlur` be `true`
- New prop `searchOnInputChange`, when it is `true`, `onSearch` will be triggered every time after input changed. The default value is `false`.
- New prop `blockDuplicateValueSearch`, when it is `true`, `onSearch` will not be triggerd if input value is same with last time searching.
- New prop `blockEmptyValueSearch`, when it is `true`, `onSearch` will not be triggerd if input value is empty.
- Rename prop `input` to be `inputProps`.
- [Core] update `<SearchInput>` styles.
- Breaking changes: …
> Refactor <SearchInput>

- CHANGELOG.md
- packages/form/package.json
- packages/form/src/TextInputRow.js
- packages/form/src/__tests__/TextInputRow.test.js
- yarn.lock
Enhance `<TextInputRow>` for custom rendering and textarea autosizing.
- [Form] Enhance `<TextInputRow>`:
- Can render custom input by `renderInput` or `inputComponent` prop.
- Can specify textarea autosize rules by `minRows` and `maxRows` props.
none.
none.
> Enhance <TextInputRow> for custom rendering and textarea autosizing

- CHANGELOG.md
- packages/core/src/Popover.js
- packages/core/src/mixins/__tests__/closable.test.js
- packages/core/src/mixins/closable.js
- packages/core/src/styles/Closable.scss
The `closable()` mixin used to bind event listeners directly to both its wrapper `<div>` and `document` to detect inside/outside clicks.
This PR achieve this by using React's own SyntheticEvent mechanism instead, so it's easier for user to choose to intercept default behaviors using simple event callbacks within React.
This PR also removed `touchend` listeners from `closable()` mixin as browsers on touch devices eventually simulates `click` events for you.
- [Core] Refactored `closable()` mixin to listen to `click` events using React SyntheticEvent.
- [Core] `<Popover>` is updated to report inside clicks to `closable()` mixin.
Both `closable()` and `<Popover>` are affected by this PR.
But their public props remain the same, so I believe it doesn't have to ring the breaking alarm.
> Refactor 'closable()' mixin to use React's own events mechanism

- packages/storybook/.storybook/webpack.config.js
Fix `yarn start` not work due to adding custom minimizer in #204 . Thank @zhusee2 for discovering this issue.
Before review it's recommended to run `yarn start` to see if it works in dev and also `yarn build:storybook` in `packages/storybook` to see if the build keeps component name in production.
- Check `defaultConfig.optimization` exists and production env before adding custom minimizer in storybook webpack config.
None.
None.
> [Storybook] Fix yarn start not work due to adding minimizer in dev env #trivial

- CHANGELOG.md
- packages/core/src/Avatar.js
- packages/core/src/__tests__/Avatar.test.js
- packages/core/src/index.js
- packages/core/src/mixins/rowComp.js
- packages/core/src/styles/Avatar.scss
- packages/form/src/SelectOption.js
- packages/form/src/SelectRow.js
- packages/form/src/__tests__/SelectRow.test.js
- packages/storybook/examples/core/Avatar/BasicAvatar.js
- packages/storybook/examples/core/Avatar/index.js
- packages/storybook/examples/core/Checkbox/BasicCheckbox.js
- packages/storybook/examples/core/List/NormalList.js
- packages/storybook/examples/form/SelectRow/WithAvatar.js
- packages/storybook/examples/form/SelectRow/index.js
In our project in development, there is a need to add users' avatars alongside the text of `<ListRow>`, `<SelectRow>`, and `<SelectOption>`.
With this in mind, we add the following three types (square, rounded, and circle) of `<Avatar>`s to display an image along with the text, and change related components to accommodate the avatars.
- Add `<Avatar>`
- Change `rowComp()` to allow the appearance of `<Avatar>` alongside the text 
- Change `<SelectRow>` and `<Checkbox>` to display `<Avatar>`
The change of `rowComp()` allows any components wrapped with it to integrate `<Avatar>` on its left. However, since `<Avatar>` is an experimental feature in a project, components except`<ListRow>` and `<SelectRow>` have not been tested and documented.
> Add <Avatar> to display an image along with the text

- CHANGELOG.md
- packages/imageeditor/src/__tests__/index.test.js
- packages/imageeditor/src/index.js
- packages/imageeditor/src/styles/index.scss
enhance <ImageEditor> for get canvas and controllable scale.
- [ImageEditor] Add new instance method `getImageCanvas()` to get current image canvas element.
- [ImageEditor] Add new props `scale` & `onScaleChange` to make scale value of editor can be controlled.
none.
none.
> Enhance <ImageEditor> for get canvas and controllable scale

- packages/form/src/TextInputRow.js
- packages/form/src/__tests__/TextInputRow.test.js
This PR allows passing uncertain `children` to form `<TextInputRow>` as before.
> Allow passing children to <TextInputRow> #trivial

- CHANGELOG.md
- packages/core/package.json
- packages/form/package.json
- packages/form/src/SelectList.js
- packages/form/src/SelectRow.js
- packages/form/src/__tests__/SelectList.test.js
- packages/form/src/__tests__/SelectRow.test.js
- packages/form/src/utils/parseSelectOptions.js
- packages/imageeditor/package.json
- packages/storybook/examples/form/SelectList/MultipleControlled.js
- packages/storybook/examples/form/SelectList/MultipleMinCheck.js
- packages/storybook/examples/form/SelectList/MultipleReadOnlyOption.js
- packages/storybook/examples/form/SelectList/MultipleUncontrolled.js
- packages/storybook/examples/form/SelectList/MultipleWithoutCheckAll.js
- packages/storybook/examples/form/SelectList/SingleControlled.js
- packages/storybook/examples/form/SelectList/SingleUncontrolled.js
- packages/storybook/examples/form/SelectRow/BasicUsage.js
- packages/storybook/examples/form/SelectRow/Customize.js
- packages/storybook/examples/form/SelectRow/MultipleValues.js
- packages/storybook/examples/form/SelectRow/WithAvatar.js
- yarn.lock
Refactor <SelectList> & <SelectRow>.
- [Core] setup `warning@4.0.3`.
- [Form] setup `warning@4.0.3`.
- [ImageEditor] setup `warning@4.0.3`.
- [Form] `<SelectList>`:
- Rename prop `values` to `value`, and it receive a single value directly when is not `multiple`, and receive an array when `multiple` is true.
- Rename prop `defaultValues` to `defaultValue`, and it receive a single value directly when is not `multiple`, and receive an array when `multiple` is true.
- Rename prop `allOptionLabel` to `checkAllLabel`.
- [Form] `<SelectRow>`:
- Rename prop `values` to `value`, and it receive a single value directly when is not `multiple`, and receive an array when `multiple` is true.
- Rename prop `defaultValues` to `defaultValue`, and it receive a single value directly when is not `multiple`, …
> Refactor <SelectList> & <SelectRow>

- CHANGELOG.md
- packages/core/src/styles/Section.scss
- packages/core/src/styles/_variables.scss
- packages/form/src/SelectRow.js
- packages/form/src/SwitchRow.js
- packages/form/src/__tests__/SelectRow.test.js
- packages/form/src/__tests__/SwitchRow.test.js
- Update title style for `<Section>`.
- Increase bottom margin for `<Section>`.
- Update form rows to use vertically-reversed layout.
> Update component styles 

- CHANGELOG.md
- packages/imageeditor/src/index.js
The `getImage()` method of `react-avatar-editor` returns a canvas with “the same resolution as the original image”. If you need the canvas to be in the dimension of editor, you'll have to call `getImageScaledToCanvas()` instead. However it's not intuitive in our own usage.
https://www.npmjs.com/package/react-avatar-editor#accessing-the-resulting-image
In this PR I'm changing the `getImageCanvas()` method in our own `<ImageEditor>` to expose the resized canvas by default. If you need its original behavior, which returns the canvas at the input image's original dimension, pass in `getImageCanvas({ originalSize: true })` instead.
> Update <ImageEditor> to give canvas in the same size of editor by default

- packages/imageeditor/src/__tests__/index.test.js
The tests are broken in #220 but that PR was merged accidentally.
This PR updates relevant tests for the just-changed `<ImageEditor>` API.
> Update tests for <ImageEditor> to reflect 'getImageCanvas' API change #trivial

- CHANGELOG.md
- package.json
- yarn.lock
Upgrade packages to reduce security alerts from Github and NPM Audit.
This PR also cleans up some duplicate packaged in lock-file using `yarn-duplicate` tool.
The main diff is in `yarn.lock`.
> Resolve security alerts

- package.json
This restores the v2 behavior.
When we were auto-releasing a canary build for #220, we found it only published a new build for `@ichef/gypctete-imageeditor`. Unfortunately the version of `@ichef/gypcrete` listed in that build remains `^3.0.0` because the two packages were not published at the same time.
By force-publish packages all together, we can at least be sure their dependencies would be correct.
> [Fix] Force publish all packages when releasing canary #trivial

- CHANGELOG.md
- packages/core/src/ColumnView.js
- packages/core/src/Modal.js
- packages/core/src/__tests__/ColumnView.test.js
- packages/core/src/__tests__/Modal.test.js
- packages/core/src/styles/ColumnView.scss
- packages/core/src/styles/Modal.scss
- packages/core/src/styles/_variables.scss
- packages/core/src/utils/wrapIfNotElement.js
- packages/storybook/examples/core/Modal/ClosableModalExample.js
- packages/storybook/examples/core/Modal/index.js
- packages/storybook/examples/core/SplitView/BasicUsage.js
- packages/storybook/examples/core/SplitView/ContainsColumnView.js
- packages/storybook/examples/core/SplitView/InsideColumnView.js
- packages/storybook/examples/core/SplitView/index.js
- packages/storybook/utils/getPropTables.js
The primary goal is to replace the inner layout of `<Modal>` with `<ColumnView>`.
It should turn on momentum scrolling on iPads, as well as a default bottom padding.
- [Core] The `bottomPadding` prop is removed. Please use `bodyPadding` prop and pass an object instead.
- [Core] `<Modal>` is refactored to render a `<ColumnView>` as its inner layout.
- [Core] `<Modal>` no longer takes `size`  and `bodyClassName` props.
- [Core] `<Modal bodyPadding>` prop now takes the same object and is passed to `<ColumnView>`.
- [Storybook] Examples for `<SplitView>` is refactored so they can be reused.
> Refactor <ColumnView> and <Modal>

- .gitignore
- CHANGELOG.md
- babel.config.js
- configs/.eslintignore
- packages/core/package.json
- packages/form/package.json
- packages/imageeditor/package.json
All packages now instead exports CommonJS modules via `"main"` field in `package.json`, while still providing ES modules via `"module"` field.
This follows the convention of bundling tools like Webpack, which tends to look for ES modules via `"module"` field before obtaining from `"main`".
- https://webpack.js.org/configuration/resolve/#resolvemainfields
> Change exported module types

- yarn.lock
Patch `handlebars` to avoid security breaches.
This PR also reduces duplicate dependency packages with `yarn-deduplicate`.
> Patch handlebars for security vulnerability

- packages/core/src/mixins/__tests__/closable.test.js
- packages/core/src/mixins/closable.js
As title. In #249 I mentioned this bug.
Anchored popover is a <Popover> wrapped with two HOCs:
`closable()(anchored()(Popover)`
Before this commit it will form following DOM structure:
```html
<body>
<div class="gyp-base-layer">
<div class="gyp-closable>
<div class="gyp-popover gyp-popover--top">
</div>
</div>
</body>
```
`gyp-popover` is absolutely positioned, with `top` value which
is relative to its document top left corner. `gyp-closable` is
`position: fixed` with `width: 100vw` and `height: 100vh`.
It works when document is too short to scroll, such as previous
storybook doc canvas. But when the element triggering popover is
over the screen(i.e. we have to scroll to click it), the position
of anchored popover will be wrong because the `position: absoulte`
of `gyp-popover` is relative …
> Fix anchored popover top position when document is scrollable

- packages/core/src/styles/Modal.scss
Asana: https://app.asana.com/0/347798529122928/1161341114084393
This fix that when centering modal (`<Modal centered />`) the modal width is too wide. Also see https://github.com/iCHEF/gypcrete/pull/248#discussion_r375179006
- `Modal.scss`. Define centered modal flex-basis and flex-grow.
None. Since on cloud2 there's no centered modal
> Fix centered modal width

- CHANGELOG.md
- packages/core/src/List.js
- packages/core/src/ListRow.js
- packages/core/src/__tests__/ListRow.test.js
- packages/core/src/styles/List.scss
- packages/core/src/styles/ListRow.scss
- packages/core/src/styles/_variables.scss
- packages/storybook/examples/core/List.stories.js
調整 `<List>` & `<ListRow>` 以更好的解決 nested list 時的樣式顯示
由於 nested list 搬出原本 list row body 之外了，所以 hover 樣式重疊的問題也一併被解決
縮排且上下 `margin` 自動消失
縮排且上下 `margin` 自動都變成 1.5 rem (預設 `margin-bottom` 為 3rem)
- [Core] Update `<ListRow>` & `<List>` styles for supporting nested list better.
none.
> Better supporting for nested list styles

- CHANGELOG.md
- packages/form/src/mixins/__tests__/formRow.test.js
- packages/form/src/mixins/formRow.js
- Asana: https://app.asana.com/0/347798529122928/1163674165898705
- 在使用 SelectRow 傳入 rowProps 時，由於 prop 名稱相同，會直接把 mixin 原本計算的 rowProps 覆蓋掉，應該修正這個行為，改成 merge props
- 在 mixin 中 將 rowProps 做 merge，並且讓傳入 mixin 中的 rowProps 優先權高於 mixin 計算的 rowProps。(這部分直接看測試情境應該會比較清楚)
> Fix formRow did not merge rowProps

- CHANGELOG.md
- package.json
- scripts/deploy.sh
- Fix deploy script to correctly push back converted tags, which will be used by `lerna` for determining version.
- Always bump `minor` when releasing canary builds.
> Fix deploy script to push tags

- packages/core/src/mixins/closable.js
修正在 `<SelectRow>` 開啟選項的 popover 並在裡面點選後，在外面按一下不會關掉 popover 的問題，必須按兩下。
這是因為修正了 #250 後，改變了 DOM 的結構讓 gyp-closable 不再是 `WrappedComponent` 的父元素，卻忘了拿掉原本在 `<WrappedComponent>` 內部點擊、觸發 gyp-closable click event handler 時不要執行 onClose 的機制。現在在 `<WrappedComponent>` 內點擊本來就不會觸發 gyp-closable 的 click handler，所以也不用額外這樣做。
實作上就是拿掉 `closable` 的 `this.insideClick` 變數。
- 拿掉 `closable` 裡面的 `this.insideClick`。
所有使用 `<Popover>` 的 component(在 gypcrete 裡面只有 `<SelectRow>`)
> [Bugfix] Fix that we have to click twice to close gyp-closable after click in wrapped component

- packages/core/src/Modal.js
- packages/core/src/SearchInput.js
- packages/core/src/Section.js
- packages/core/src/StatusIcon.js
- packages/core/src/Tag.js
- packages/core/src/Text.js
- packages/core/src/TextEllipsis.js
- packages/form/src/SelectList.js
修改了下列的 component，讓所有的 gypcrete component 都可以帶 props 到最外層的元素上，用於加 test id。例如 `<List data-test-id="menu-item-list" />`。
- `<Modal>`
- `<Section>`
- `<SearchInput>`
- `<StatusIcon>`
- `<Tag>`
- `<Text>`
- `<TextEllipsis>`
- `<SelectList>`
有一些已經把 remaining props 放在內層元素上，所以沒有修改：
- `<TextInput>`
props 會傳到裡面的 `<input>`
- `<SelectOption>`
props 會傳到裡面的 `<Checkbox>`，外層的 `<ListRow>` 吃不到。
- `<ImageEditor>`
props 會傳到 `react-avatar-editor` 上面
一些 component 裡面的元素也許想要加 props 進去：
- `<Section>`(即 `<List>`)
裡面有 title 和 desc
- `<SearchInput>`
裡面有 search button 和 input
- `<StatusIcon>`
裡面有 `<Icon>`
- `<Switch>`
裡面有 checkbox input
- `<Text>`
裡面有 basic 和 aside
- `<SelectList>`
全選的 option 沒辦法傳 props 進去
- `<SelectRow>`
裡面的 `<Text>` 和 `<Popover>` 沒辦法傳 props 進去，`<ListRow>` 和 `<SelectList>` 已經有了
- `<SwitchRow>`
裡面的 …
> [Feature] Allow passing remaining props to wrapper element to add attribute (e.g. test id)

- CHANGELOG.md
- packages/core/package.json
- packages/core/src/SearchInput.js
- packages/core/src/StatusIcon.js
- packages/core/src/Text.js
- packages/core/src/utils/getRemainingProps.js
- packages/storybook/examples/core/Text.stories.js
- yarn.lock
- 修正在 #267 中誤把不合法的 props 往下傳給 DOM element 的問題；為此添加了 `lodash.omit` 的 dependency。抽出了 `getRemainingProps` 的 utility。
- 也順手修掉 `<Text>` story 中噴出來的 error message，起因於錯誤的 import `<StatusIcon>`
> [Bugfix] Fix passing invalid props to dom element

- packages/form/src/SelectList.js
修掉 `<SelectList>` 裡面誤傳了帶有 `SelectList` 自身的 props 的 bug。會導致底下 `<SelectRow>` 的 `onChange` 出問題。Same as #269.
> Fix SelectList wrapperProps

- CHANGELOG.md
- packages/core/src/Popup.js
- packages/core/src/__tests__/Popup.test.js
Asana: https://app.asana.com/0/347798529122928/1180565159757507
去掉 `<Popup>` 裡面對 buttons 額外確認 element type、如果不是 `<PopupButton>` 就當作 props 丟進 `<PopupButton>` 的行為。
這個舊行為會使得我們傳包住 `<PopupButton>` 的 element 到 `buttons` 時噴錯，因為只要包了 component，type 就不再是 `PopupButton`。
確認過我們目前沒用到這個行為了。
> Remove deprected PopupButton type check

- CHANGELOG.md
- packages/core/src/mixins/rowComp.js
- packages/core/src/styles/_states.scss
- packages/core/src/utils/__tests__/getStateClassnames.test.js
- packages/core/src/utils/getStateClassnames.js
- packages/storybook/examples/core/Button.stories.js
Asana: https://app.asana.com/0/347798529122928/1179698171481649
下列的 component 會新增 `muted` prop，`muted` 為 `true` 時，會有 `disabled` 的樣式，但 click 時仍會觸發事件。
- `<Button>`
- `<Checkbox>`
- `<SearchInput>`
- `<Switch>`
- `<TextInput>`
- `<TextLabel>`
- `<ListRow>`
實作上就是讓 `rowComp()` mixin 可以吃 `muted`，新增 `.gyp-state-muted` 的樣式，參照 `.gyp-state-disabled` 但拿掉 `pointer-events: none` 的限制。
> Add muted prop on `rowComp()`

- CHANGELOG.md
- packages/core/src/Popup.js
- packages/core/src/__tests__/Popup.test.js
- packages/core/src/styles/Popup.scss
- when `message` prop of `<Popup>` is a string, pass it to `<PopupMessage>` as `title` prop.
> Pass message as messageTitle when type is string in Popup

- .gitignore
WebStorm automatically generates config files under `.idea/` directory which shouldn't be in version control
- Added .idea to gitignore
N/A
N/A
> [Chore] Add WebStorm generated .idea directory to gitignore

- CHANGELOG.md
- packages/core/src/Section.js
- packages/core/src/styles/Section.scss
- packages/storybook/examples/core/List.stories.js
在 `<List>` / `<Section>` 中加入 title 右方的區域。整個 `gyp-section--title` 變為 flex 排版。
另外和設計確認過，也將 title 的 padding 從 1px 改為 5px。
> [Feature] Add title right area on Section / List

- packages/core/src/icons/components/MinusOne.js
- packages/core/src/icons/components/PlusOne.js
- packages/core/src/icons/components/index.js
- packages/core/src/icons/svg/minus-one.svg
- packages/core/src/icons/svg/plus-one.svg
- 新增兩個改變數量的按鈕，plus-one/minus-one，用來改變交易明細列印設定裡面的預設張數
- plus-one:
- minus-one:
> New icons: plus-one and minus-one

- packages/core/src/styles/Section.scss
#297 實作 `<Section>` / `<List>` 的 title right area 後，設計要求區塊的左邊要有 5px 間隔。
> Add padding left for section title right area

- CHANGELOG.md
- packages/core/src/Popup.js
- packages/core/src/__tests__/Popup.test.js
- packages/storybook/examples/core/Popup.stories.js
This PR gives up the `message={{ title, desc }}` prop format introduced in #292, switching to `title` + `message` props instead. So it's easier to toggle the optional `title`.
> Revise <Popup> rev.2

- CHANGELOG.md
- packages/core/src/Popover.js
- packages/core/src/mixins/anchored/__tests__/getPositionState.test.js
- packages/core/src/mixins/anchored/getPositionState.js
- packages/core/src/mixins/anchored/index.js
修正當 placement 設定為向下 (`bottom`) 的 popover 下方空間不足時往上長，結果導致看不到 popover 上半部的問題。
這是因為現在 `anchored` 的邏輯，在原本的 placement 向下且空間不足時，就會往上。因此當 popover 的內容沒有出現捲軸(不超過 `max-height`)，但又比上方空間長時，popover 上面的東西就點不到。
~解法：當 popover 的 placement 設定為向下，且下方和上方的空間都不足時，還是向下長。缺點是有機會破圖，但相對不能按應該還是好些。~
根據後續的討論，改成在上下都不夠顯示 popover 時，用空間較足夠的那邊作為 placement。並且計算剩餘空間給下面的 `<Popover>` 作為 `max-height` 來確保不會高到破版。
會影響到 `<Tooltip>` 和 `<Popover>` 在 placement 設為 bottom 且上下空間都不夠時的行為，其餘不影響。
> Fix popover placement when there is no enough space on top or bottom of content

- packages/form/src/SwitchRow.js
- `SwitchRow` disabled 時，其中的 `TextLabel` 是以非 `bold` 的樣式顯示，現在修改為 `disabled` 樣式。
- 這個修改同時影響到 disabled 以及 readOnly 兩個 style，也就是說當 `SwitchRow` readOnly 時，其中的 `TextLabel` 也是以 `disabled` 的樣式顯示。
Before:
After:
- 掃過一次 cloud/frontend，沒有 component 用到 SwitchRow 的 `disabled` or `readonly`，所以基本上沒有影響
> 修改 SwitchRow disabled style

- packages/core/src/Popup.js
- packages/core/src/__tests__/Popup.test.js
- packages/core/src/styles/Popup.scss
- packages/storybook/examples/core/Popup.stories.js
讓 Popup 的 `message` 遇到換行字元 e.g. `\n` 的時候可以顯示換行
- 新增 `white-space: pre-line`，讓文字可在有換行字元時換行
- 新增 `with-title` 的 modifier class 並將原本 `message-desc` 的樣式移入
- 由於 `message` 在有 `title` 跟沒有 `title` 的狀況下會有不同樣式（字體大小、顏色等），所以分開處理
> [Popup] Make Popup message able to display line break with newline characters

- packages/core/src/ListRow.js
- packages/core/src/mixins/withStatus.js
- packages/core/src/styles/ListRow.scss
- Let ListRow errorMsg support array of React node.
- Fix p tag wrap other tag.
- ListRow.js
> [Bugfix] Change errorMsg prop type to array

- packages/core/src/mixins/anchored/index.js
在製作 https://github.com/iCHEF/cloud-frontend/pull/961 的時候，發現原本的設定會導致 Popover 在不傳 `remainingSpace` 的時候報錯：
但根據[這行](https://github.com/iCHEF/gypcrete/blob/develop/packages/core/src/Popover.js#L51)，推測該 props 應非必填 props
移除`remainingSpace` props 的必填設定
> Remove isRequired of anchor props  'remainingSpace'

- .github/auto_assign.yml
- CHANGELOG.md
- packages/core/src/EditableTextLabel.js
- packages/core/src/__tests__/EditableTextLabel.test.js
- Change `onTouchStart` to `onTouchEnd` in `EditableTextLabel`.
- Because react dnd multi-backend would dispatch  a cloned version of the touchstart event, it would make `handleTouchStart` event handler in `EditableTextLabel` executed twice.
> Bugfix: Change EditableTextLabel to listen touchEnd event

- CHANGELOG.md
- packages/core/src/List.js
- packages/core/src/styles/List.scss
- packages/core/src/styles/ListRow.scss
- packages/core/src/styles/_variables.scss
- packages/storybook/examples/core/List.stories.js
Adds an `topArea` for any content that's below `<Section>` title but above all `<ListRow>`s. 
If the area exists, the first `<ListRow>` should receive an additional top shadow as separator.
No, it's a new prop which does not affect existing codes.
> Add 'topArea' to <List>

- packages/form/src/SwitchRow.js
- packages/form/src/styles/SwitchRow.scss
- Fix `Switch` is overflow hidden in `SwitchRow` with setting minified true.
> [Bugfix] Switch is overflow hidden in SwitchRow

- packages/form/src/SelectRow.js
修掉 `<SelectRow>` 在找不到 value 對應的 label 時，仍會把空的值 join 起來做成 rowValueLabel 導致多了不需要的分隔符號的問題。
e.g. value = ['a','b'], labelMap = { a: 'a', }, separator = '/'，則 SelectRow 的 valueLabel 應該要是 `a`，因為找不到 b 對應的 label。
現在會變成 `a/`，因為它在 labelMap 找不到對應的 value key 時仍然會把 undefined join 成 valueLabel。
> [Bugfix] remove empty label when build value label in <SelectRow>

- CHANGELOG.md
- packages/core/src/mixins/__tests__/closable.test.js
- packages/core/src/mixins/anchored/__tests__/getPositionState.test.js
- packages/core/src/mixins/anchored/__tests__/index.js
- packages/core/src/mixins/anchored/getPositionState.js
- packages/core/src/mixins/anchored/index.js
- packages/core/src/mixins/closable.js
- Add `skip` in `closable` to remove closable layer in runtime. e.g. remove closable layer temporarily for `<Popover />`
- Add `refreshOnWindowResize` on `anchored` to keep anchored node position on resize.
- Add `distanceFromAnchor` on `anchored`, which determine the distance between anchor and anchored node (default is 0, which is current behavior).
> Add `skip` in closable, `refreshOnWindowResize` and `distanceFromAnchor` in `anchored`

- CHANGELOG.md
- packages/core/src/mixins/rowComp.js
- packages/core/src/styles/RowComp.scss
- packages/storybook/examples/core/Button.stories.js
讓 RowComp 內的 Text aside，在 disabled 時仍可以觸發 onClick。
用在 button 本身 disabled，但敘述文字帶有連結或其它 control 而需要 clickable 的時候。
範例見 [storybook](https://deploy-preview-325--gypcrete.netlify.app/?path=/docs/ichef-gypcrete-button--basic-usage#aside-control-clickable-on-disabled-button)
> add aside clickable on disabled in RowComp

- CHANGELOG.md
- packages/core/src/TextInput.js
- packages/core/src/__tests__/TextInput.test.js
- packages/core/src/styles/TextInput.scss
- packages/storybook/examples/core/TextInput.stories.js
- packages/storybook/examples/form/TextInputRow.stories.js
Add `postfix` prop for `<TextInput>` to show postfix in `<TextInput>` and `<TextInputRow>`
> Add postfix for `<TextInput>`

- packages/core/src/styles/Popup.scss
起因是有個 [後台 popup 無法正常顯示的 issue](https://app.asana.com/0/1201530847918073/1201995968067616/f)，經查後發現多餘的 css 屬性在 Ipad OS 15.4 的瀏覽器上出問題(詳見 PR 註解)，應該是個 ios 15.4 的 bug，這邊就先拔掉修正此問題
https://user-images.githubusercontent.com/47882138/159432700-415abde0-4edf-4865-a3e1-c7769c574c02.mov
> 移除不必要的 css 屬性

- CHANGELOG.md
- packages/core/src/mixins/rowComp.js
- packages/core/src/styles/RowComp.scss
`asideControlClickableOnDisabled` prop should not applied if `disabled` prop is `false`, or the click event handler on `rowComp()` wont trigger.
> [Bugfix] Should not apply asideControlClickableOnDisabled if not disabled

- .nvmrc
- package.json
先前沒有特別指定 node version，但實際上如果用 > 12 的版本 node sass 會炸裂，無法正常跑 yarn start 等指令
所以這邊處理
1. 在 package.json 指定版本：雖然是建議性質沒有強制，但可讓開發者參考
2. 新增 .nvmrc：讓有用 nvm 的開發者可自動切換到指定版本
Ref: 
1. https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines
1. https://github.com/nvm-sh/nvm#nvmrc
> [Chore] 指定 Node version

- packages/core/src/icons/components/CheckboxEmpty.js
- packages/core/src/icons/components/CheckboxHalf.js
- packages/core/src/icons/components/CheckboxSelected.js
- packages/core/src/icons/components/index.js
- packages/core/src/icons/svg/checkbox-empty.svg
- packages/core/src/icons/svg/checkbox-half.svg
- packages/core/src/icons/svg/checkbox-selected.svg
- packages/core/src/styles/Checkbox.scss
- 底下框起來的三個 svg 元件都是與 checkbox 相關的元件，但他的命名都是 Radio 開頭，與接下來要實作的 RadioSelectList 相衝突，所以先把他們名稱改掉
附上接下來會加進來的 RadioSelectList 示意圖
> [RasioSelectList] rename 原有的 checkbox 相關的 svg 檔案

- CHANGELOG.md
- packages/core/src/index.js
- packages/form/src/RadioSelectList.js
- packages/form/src/RadioSelectOption.js
- packages/form/src/SelectList.js
- packages/form/src/utils/__tests__/parseSelectOptions.test.js
- packages/form/src/utils/parseSelectOptions.js
- packages/storybook/examples/form/RadioSelectList.stories.js
- RadioSelectList 是基於 SelectList 的再封裝，只是把一些 props 寫死在裡面
- RadioSelectOption 和 SelectOption 也是 9 成像，只差在一個是 Radio 一個是 Checkbox
> [RadioSelectList] 實作 RadioSelectList, RadioSelectOption

- yarn.lock
這是漏洞套件更新計畫 part 1
先將 dependabot 能夠自動產生 PR 的列出來，從中檢視確認沒有 breaking change 疑慮的 ，優先處理升級
有簡單在 storybook 把 component 都玩過一次，看起來沒有問題
build(deps): bump `merge-deep` from 3.0.2 to 3.0.3 (4371139)
build(deps): bump `url-parse` from 1.4.3 to 1.5.10 (8f45060)
build(deps): bump `handlebars` from 4.6.0 to 4.7.7 (064faa8)
build(deps): bump `async` from 2.6.0 to 2.6.4 (9b1d447)
build(deps): bump `moment` from 2.24.0 to 2.29.3 (07d4c98)
build(deps): bump `tmpl` from 1.0.4 to 1.0.5 (1e451aa)
build(deps): bump `tar` from 2.2.1 to 2.2.2 (d323db1)
build(deps): bump `ua-parser-js` from 0.7.18 to 0.7.31 (a637d76)
build(deps): bump `ssri` from 6.0.1 to 6.0.2 (fec9a05)
build(deps): bump `lodash` from 4.17.15 to 4.17.21 (650472d)
build(deps): bump `pug-code-gen` from 2.0.2 to 2.0.3 (888e04a)
build(deps): bump …
> [gypcrete] 更新漏洞套件 pt.1

- .github/workflows/release.yml
- Asana Link: https://app.asana.com/0/347798529122928/1202303543909577/f
- 把 gypcrete, gypcrete2, fe-modules 都加上自動發 backport 和 slack 提醒。composite action: https://github.com/iCHEF/release-backport-action
> ci: add auto backport

- packages/core/src/List.js
- packages/core/src/Section.js
- packages/core/src/__tests__/Section.test.js
- packages/core/src/styles/Section.scss
iPF M2 專案申請 / 解綁表單有用到 SelectList，spec 希望能處理 SelectList 欄位為空的情境，需要調整 Section 讓其支援錯誤顯示。錯誤文字會顯示在整塊 Section 底部
> [Section] 支援顯示錯誤訊息

- packages/core/src/mixins/anchored/__tests__/getPositionState.test.js
- packages/core/src/mixins/anchored/__tests__/placementStrategies.test.js
- packages/core/src/mixins/anchored/constants/placement.js
- packages/core/src/mixins/anchored/getPositionState.js
- packages/core/src/mixins/anchored/placementStrategies.js
這支 PR 及其後續 #391 #392 #393 讓 Popover (`anchored`) 可以支援置於 anchor 的左 / 右方。之前只能置於上下。
修改的步驟如下：
1. 將 `getPositionState()` 對 top / bottom 方向的計算各自封裝到 `top / bottom placementStrategy` 的物件下。 (#390, #391)
`getPositionState()` 是用來計算 popover / tooltip 相對於 anchor 的位置。若要加入左右方向，依現在的結構會有點困難：
- 由於之前只需支援上下兩方向，直接在 function 內用 condition 來判斷應回傳的結果([例子](https://github.com/iCHEF/gypcrete/blob/558abdad602b3b5f147b759a57e501e215c3ef1f/packages/core/src/mixins/anchored/getPositionState.js#L87-L92))。
- getPositionState 中使用的 getTopPosition 和 getLeftPositionSet 只吃計算 top / bottom 時需要的參數，要再包含 left / right 所需的參數又更多
- 原本 top / bottom 時 popover 的 arrow 位置計算是在 getLeftPositionSet 之下，但 left / right 時應該要是 getTopPositionSet。
因此這支 PR 引入了 placement strategy 的概念，每個 placement strategy 會對應到一個方向，並實作下列的 function
(1) 被 anchor 的 UI …
> [Anchor] Support left / right direction (pt. 1 - refactor getPositionState with placement strategies)

- packages/core/src/Popover.js
- packages/core/src/__tests__/Popover.test.js
- packages/core/src/mixins/anchored/__tests__/index.js
- packages/core/src/mixins/anchored/getPositionState.js
- packages/core/src/mixins/anchored/index.js
- packages/core/src/styles/Popover.scss
- packages/storybook/examples/core/Popover.stories.js
讓 popover 可以套用 left / right 的 placement，並加入 anchored right popover 的 story。
> [Anchor] Support left / right direction (pt. 4 - add horizontal placement prop on Popover)

- packages/core/package.json
- packages/core/src/contexts/listSpacing.js
- packages/form/package.json
- yarn.lock
- Fix react version not match warnings when install packages
- upgrade react-textarea-autosize from v7 to v8
- replace create-react-context with  native React Context API
> Upgrade react to v17 - resolve packages not match react 17

- packages/core/src/mixins/__tests__/renderToLayer.test.js
- packages/core/src/mixins/renderToLayer.js
To enable adjusting zIndex of base layer of `<Popup />` or `<Popover />`, added `zIndex` prop on `renderToLayer` HOC.
> Add zIndex prop to renderToLayer HOC

- packages/form/src/SelectList.js
- packages/form/src/__tests__/SelectList.test.js
- 重構有使用到 UNSAFE lifecycle 的 components，用 react hooks 改寫
- 由於從 class component 改寫成 functional component，原本的 enzyme 測試針對 class component 的測試方法會失敗，因此也將對應的測試用 testing-library 重寫了
- 這個 PR 只改寫了 SelectList，因為內容比較複雜、重寫的測試情境也滿多的，單獨發一個 PR
> refactor: Refactor SelectList component to use React hooks

- packages/form/src/SelectRow.js
- packages/form/src/SwitchRow.js
- packages/form/src/__tests__/SelectRow.test.js
- packages/form/src/__tests__/SwitchRow.test.js
- packages/storybook/examples/form/SelectRow.stories.js
- 重構有使用到 UNSAFE lifecycle 的 components，用 react hooks 改寫
- 由於從 class component 改寫成 functional component，原本的 enzyme 測試針對 class component 的測試方法會失敗，因此也將對應的測試用 testing-library 重寫了
- 這個 PR 改寫了 SelectRow 和 SwitchRow ，並更新對應的測試
- 建議依照 commit review
> refactor: Refactor SelectRow component to use React hooks

- packages/imageeditor/src/ImageEditor.js
- 為了更新 React 18，將原本的 UNSAFE_componentWillReceiveProps 的部分改成 componentDidUpdate，因為沒有改寫成 functional component，原本的 enzyme 測試就不需要改
- 另外補充為什麼不改寫成 functional component 的原因：原本的 ImageEditor 程式碼似乎有刻意利用 class component 的特性去提供 `getCroppingRect`、`getImageCanvas` 等方法讓外部調用，由於此次目的不在重構成 functional component，想盡可能減少 API 變動的風險，所以決定維持 class component，只替換掉 unsafe lifecycle 就好
> refactor: Refactor componentDidUpdate in ImageEditor.js

- .github/workflows/storybook.yml
- .gitignore
- packages/storybook/package.json
- yarn.lock
[Asana](https://app.asana.com/0/347798529122928/1206472623204605/f)
[Storybook Preview](https://65b8bed5715da3cedaa01e0e-icngnxwbbr.chromatic.com/?path=/story/gypcrete-avatar--basic-usage)
整合 Chromatic，把文件從 Netlify 換到 Chromatic 上
因為改了原本輸出 static files 的資料夾 (改成 Storybook 的預設值 `storybook-static`)，Netlify 的 CI 會失敗是預期的
> feat: integrate storybook with chromatic

- packages/core/src/mixins/__tests__/rowComp.test.js
- packages/core/src/mixins/rowComp.js
- packages/core/src/styles/_states.scss
- [Asana task](https://app.asana.com/0/347798529122928/1207042998264153/f)
最近在寫測試的時後發現 gypcrete 的 TextInput disabled 狀態不會有 disabled attribute，導致有點難驗證欄位是否停用。
查了一下原因是在 rowComp 這個 HOC 把 disabled prop 劫持後沒有往下傳，看起來應該是不小心漏掉，後續發現可能是為了避免樣式上對停用元素加上 opacity 導致和 `.gyp-state__disabled` 的 opacity 樣式疊加，導致 input 顏色被刷淡兩次才攔截的。
另外讓 input element 會標上 disabled html attribute 的正規作法也是有其必要的，這讓 input element 可以真正有 disabled 效果，原本會由 `rowComp` HOC 在 input 外層的 wrapper 加上 `gyp-state__disabled` class，透過 `pointer-events: none` 阻擋游標互動來模擬停用的效果，但是這樣會有一些漏洞，例如透過鍵盤 tab 仍然可以選取到停用的 input、e2e 測試如果直接選取到 input element 進行互動也可以繞過樣式的阻擋。
- 讓 `rowComp` 會將 `disabled` prop 往下傳
- TextInput 在停用狀態的 font-weight 會從 700 → 400
原本停用狀態的 TextInput font-weight 就應該要是 400，只是原先 disabled prop 被 rowComp HOC 攔截，導致 disabled 一直以來都沒有正確傳到 TextInput …
> fix: pass down disabled prop in the rowComp Hoc
