iCHEF/gypcrete

.travis.yml
CHANGELOG.md
package.json
scripts/deploy.sh
scripts/ghpages.sh

Lets CI deploy the package successfully.

[Hotfix] Fix deploy bugs

---

.travis.yml
package.json
scripts/deploy.sh

1. Prevent publishing canary builds on `master`
2. Checkout to `master` before running `lerna publish` script

Fix auto deploy on Travis CI

---

CHANGELOG.md
packages/form/package.json
packages/form/src/SelectList.js
packages/form/src/SelectOption.js
packages/form/src/__tests__/SelectList.test.js
packages/form/src/__tests__/SelectOption.test.js
packages/form/src/index.js
packages/storybook/examples/Form.SelectList/BasicUsage.js
packages/storybook/examples/Form.SelectList/MultipleControlled.js
packages/storybook/examples/Form.SelectList/MultipleMinCheck.js
packages/storybook/examples/Form.SelectList/MultipleReadOnlyOption.js
packages/storybook/examples/Form.SelectList/MultipleUncontrolled.js
packages/storybook/examples/Form.SelectList/SingleControlled.js
packages/storybook/examples/Form.SelectList/SingleUncontrolled.js
packages/storybook/examples/Form.SelectList/index.js
yarn.lock

Add a list component which can be select one or multiple values from.
1. Add new `<SelectList>` and `<SelectOption>`
2. Add examples for `<SelectList>`
3. Add tests for 2 new components.

[gypcrete-form] Add <SelectList>

---

CHANGELOG.md
lerna.json
package.json
packages/core/configs/webpack.dist.js
packages/core/package.json
packages/form/configs/webpack.dist.js
packages/form/package.json
packages/storybook/package.json

- Fixed CSS bundle requesting font files from broken path. (#108)

Release 1.3.2

---

CHANGELOG.md
lerna.json
package.json
packages/core/package.json
packages/form/package.json
packages/storybook/package.json

Fixes `@ichef/gypcrete-form` package not publishing anything.

Release 1.3.3

---

CHANGELOG.md
lerna.json
package.json
packages/core/package.json
packages/core/src/styles/Checkbox.scss
packages/form/package.json
packages/form/src/SelectRow.js
packages/storybook/package.json

Changes in this release:
- [Core] Fix `<Checkbox>` not displaying correct icons. 
- [Form] Update `<SelectRow>` to use new `dropdown` icon.

Release 1.5.1

---

CHANGELOG.md
lerna.json
package.json
packages/core/package.json
packages/core/src/Modal.js
packages/core/src/__tests__/Modal.test.js
packages/form/package.json
packages/storybook/examples/Modal/index.js
packages/storybook/package.json

- 1.7.1
-  Fix `<Modal>` not rendering its content. #139
- Remove the `Closable` HOC from `<Modal>` to prevent unexpected closing behaviors occur when more than one modals are open. #139
- Refine the showcase of `<Modal>`. #139
- [Core] Fix `<Modal>` not rendering its content (#139)
- [Core] Remove the `Closable` HOC from `<Modal>` to prevent unexpected closing behaviors occur when more than one modals are open. (#139)
- [Storybook] Refine the showcase of `<Modal>` component. (#139)

Release 1.7.1

---

CHANGELOG.md
packages/core/src/styles/ListRow.scss
packages/storybook/examples/List/NestedList.js
packages/storybook/examples/List/index.js

Update styles for nested to match design
- Add examples for nested list
- Update styles for `<ListRow>` to work with nested list

Update nested list

---

packages/core/src/styles/List.scss
packages/core/src/styles/ListRow.scss
packages/core/src/styles/Modal.scss
packages/core/src/styles/Section.scss
packages/core/src/styles/_colors.scss

Update colors for <ListRow> to better match design spec.
Add v3 color plate variables for future use.

Update colors for <ListRow>

---

.vscode/launch.json
CHANGELOG.md
configs/jest.config.json
configs/jestSetup.js
package.json
packages/core/package.json
packages/core/src/Checkbox.js
packages/core/src/__tests__/Checkbox.test.js
packages/core/src/__tests__/EditableTextLabel.test.js
packages/core/src/mixins/__tests__/renderToLayer.test.js
packages/form/package.json
packages/form/src/__tests__/TextInputRow.test.js
packages/imageeditor/package.json
yarn.lock

Upgrade to Enzyme 3 and fix broken tests to meet new Enzyme API.

Upgrade to Enzyme 3

---

CHANGELOG.md
packages/form/src/SelectOption.js

Add desc prop to <SelectOption>.
- [Form] Add `desc` prop to `<SelectOption>`
none.
none.

Add desc prop to <SelectOption>

---

packages/core/src/styles/ColumnView.scss
packages/core/src/styles/Modal.scss
packages/core/src/styles/_variables.scss
packages/storybook/examples/core/Modal/ClosableModalExample.js

This PR addresses minor style issues after the `<Modal>` and `<ColumnView>` overhaul, to make them have better display.

Minor style fixes #trivial

---

CHANGELOG.md
packages/form/src/SelectRow.js

Updates `form` `<SelectRow>` component to take empty string as `(unset)`.

SelectRow takes empty string as unset

---

packages/core/src/utils/__tests__/randId.test.js

Fix wrong test logic of `randId.test.js`

Fix randId test.

---

packages/core/src/List.js

<List> title prop support both string and node type

Let List title prop support both string and node type

---

CHANGELOG.md
packages/core/src/Popup.js
packages/core/src/__tests__/Popup.test.js
packages/core/src/styles/Popup.scss
packages/core/src/styles/_variables.scss
packages/storybook/examples/core/Popup.stories.js

Preview: https://deploy-preview-273--gypcrete.netlify.app/iframe.html?id=ichef-gypcrete-popup--basic-usage&viewMode=docs#large-popup
- Add `large` prop to `<Popup>`
- update `<Popup>` styles

Add `large` prop for large size <Popup>

---

.github/auto_assign.yml

Update auto-assign action reviewer

---

.github/auto_assign.yml

Add new reviewer to .auto_assign
- add new reviewer (a26620236)

[Chore] Add new reviewer to .auto_assign

---

packages/form/src/index.js

export parseSelectOptions from @ichef/form for draft "Dropdown" component.

export parseSelectOptions from @ichef/form for draft "Dropdown" component

---

packages/form/src/SelectRow.js

Let `<SelectRow />` can accept custom `renderRowValueLabel` prop, so user can customize the row value label text.

add renderRowValueLabel for SelectRow

---

packages/core/src/icons/components/RadioEmpty.js
packages/core/src/icons/components/RadioSelected.js
packages/core/src/icons/components/index.js
packages/core/src/icons/svg/radio-empty.svg
packages/core/src/icons/svg/radio-selected.svg

- 加入 radio-empty.svg, radio-selected.svg 及其 Svg component

[RadioSelectList] 加入 radio 相關的 svg 檔案及元件

---

CHANGELOG.md
packages/core/src/Radio.js
packages/core/src/icons/components/CheckboxEmpty.js
packages/core/src/icons/components/CheckboxHalf.js
packages/core/src/icons/components/CheckboxSelected.js
packages/core/src/icons/components/RadioEmpty.js
packages/core/src/icons/components/RadioSelected.js
packages/core/src/icons/components/index.js
packages/core/src/icons/svg/checkbox-empty.svg
packages/core/src/icons/svg/checkbox-half.svg
packages/core/src/icons/svg/checkbox-selected.svg
packages/core/src/icons/svg/radio-empty.svg
packages/core/src/icons/svg/radio-selected.svg
packages/core/src/index.js
packages/core/src/styles/Checkbox.scss
packages/core/src/styles/Radio.scss
packages/form/src/RadioSelectList.js
packages/form/src/RadioSelectOption.js
packages/form/src/SelectList.js
packages/form/src/utils/__tests__/parseSelectOptions.test.js
packages/form/src/utils/parseSelectOptions.js
packages/storybook/examples/core/Radio.stories.js
packages/storybook/examples/form/RadioSelectList.stories.js

- RadioSelectList, RadioSelectOption, Radio 元件的 merge request

[Merge Request] RadioSelectList

---

packages/form/src/index.js

[RadioSelectList] export RadioSelectList and RadioSelectOption

---

package.json
packages/core/src/__tests__/Radio.test.js
packages/form/src/__tests__/RadioSelectList.test.js
packages/form/src/__tests__/RadioSelectOption.test.js

- 補了 RadioSelectList, RadioSelectOption, Radio 元件測試
- 另外也有新增了 2 個 Svg 元件，但感覺測試這些元件意義不大，所以就不寫了

[RadioSelectList] 補測試

---

.github/workflows/canary_release.yml
.github/workflows/ci.yml
package.json

Asana Task: https://app.asana.com/0/0/1202114099601734/f
原本 Travis CD 壞掉了，這邊改用 github action 去做 canary release 的自動化

Add canary release workflow

---

.github/workflows/release.yml
package.json
yarn.lock

Asana Task: https://app.asana.com/0/0/1202244324530183/f
原本 release 流程需在 local 手動 bumpversion 後推上去，並在 github 建立一個新的 Release (ex: v3.4.5)，讓其觸發 Travis CD(詳細可看 travis.yml 和 Readme)。因為 Travis 壞掉了，這邊把原本手動升版、打 tag 和發佈的流程用 github action 做成自動化(參考 fe-modules 的 release workflow)

Add release workflow

---

packages/core/src/mixins/anchored/__tests__/getPositionState.test.js
packages/core/src/mixins/anchored/__tests__/index.js
packages/core/src/mixins/anchored/__tests__/placementStrategies.test.js
packages/core/src/mixins/anchored/getPositionState.js
packages/core/src/mixins/anchored/index.js
packages/core/src/mixins/anchored/placementStrategies.js

續 #391，實作 left / right placement strategy。

[Anchor] Support left / right direction (pt. 3 - add horizontal placement strategy)

---

packages/imageeditor/src/index.js
packages/imageeditor/src/utils/index.js

- export helper function `getInitPosition`

Export helper function `getInitPosition`

---

packages/core/src/icons/components/Upload.js
packages/core/src/icons/components/__tests__/Upload.test.js
packages/core/src/icons/components/index.js
packages/core/src/icons/svg/upload.svg

新增「upload」icon
- Asana: https://app.asana.com/0/1203653298287869/1205505274971327/f

[Icon] add "upload" icon

---

packages/core/src/EditableTextLabel.js

- 後來看了一下這個 EditableTextLabel 模擬 doubleClick  的實作，應該是要把原本存在 state 的 count 跟 timer 改成存在 ref 比較合理，畢竟這兩個資料都沒有需要 rerender，且這樣在 onTouchEnd 觸發 count 的計算時應該會是比較正確的
- 另外也加上 timer clean up 的 useEffect

refactor: Refactor EditableTextLabel component to use useRef
